CREATE OR REPLACE PACKAGE ARC_PKG AS

    PROCEDURE MERGE_BY_EXEC_ID(EXEC_ID IN NUMBER);

    PROCEDURE MERGE_BORROWER(EXECUTE_ID IN NUMBER);

    PROCEDURE MERGE_CREDIT(EXECUTE_ID IN NUMBER);

END ARC_PKG;


CREATE PACKAGE BODY ARC_PKG AS

    PROCEDURE MERGE_BY_EXEC_ID(EXEC_ID IN NUMBER)
        IS
    BEGIN
        MERGE_BORROWER(EXEC_ID);
        MERGE_CREDIT(EXEC_ID);
    END MERGE_BY_EXEC_ID;

    PROCEDURE MERGE_BORROWER(EXECUTE_ID IN NUMBER)
        IS
    BEGIN
        MERGE INTO BCP_BORROWER_ARC BBA
        USING BCP_BORROWER BB
        ON (BB.EXEC_ID = EXECUTE_ID)
        WHEN NOT MATCHED THEN
            INSERT
            VALUES (BB.OID, BB.CREDIT_ID, BB.EXEC_ID, BB.ACCOUNT_NO, BB.ROL, BB.ID, BB.NAME, BB.COUNTRY_CODE,
                    BB.DATE_OF_BIRTH, BB.PLACE_OF_BIRTH,
                    BB.PIN_CODE, BB.DOC_TYPE, BB.VLR, BB.ORG_ID, BB.PERSON_TYPE, BB.PERSON_ID, BB.IS_NEW);


        DELETE FROM BCP_BORROWER BB WHERE BB.EXEC_ID = EXECUTE_ID;
    END MERGE_BORROWER;


    PROCEDURE MERGE_CREDIT(EXECUTE_ID IN NUMBER)
        IS
    BEGIN

        MERGE INTO BCP_CREDIT_ARC BCA
        USING BCP_CREDIT BC
        ON (BC.EXEC_ID = EXECUTE_ID)
        WHEN NOT MATCHED THEN
            INSERT
            VALUES (BC.OID, BC.EXEC_ID, BC.ACCOUNT_NO, BC.CURRENCY_OF_CREDIT, BC.CREDIT_TYPE,
                    BC.INITIAL_AMOUNT_OF_CREDIT,
                    BC.CREDIT_LINE_AMOUNT, BC.DISOUT_AMOUNT_OF_CREDIT, BC.ANNUAL_INTEREST_RATE, BC.PURPOSE_OF_CREDIT,
                    BC.CREDIT_PERIOD_IN_MONTHS, BC.DATE_OF_GRANT, BC.DUE_TIME_FIRST_CONTRACT, BC.DUE_TIME_LAST_CONTRACT,
                    BC.LAST_PAYMENT_DATE, BC.MONTHLY_PAYMENT_AMOUNT, BC.DAYS_MAIN_SUM_IS_OVERDUE, BC.OIA_FOR_REPPERIOD,
                    BC.NUMBER_OF_PROLONGS, BC.CREDIT_STATUS_CODE, BC.BANKRUPTCY_STATUS, BC.COLL_TYPE_CODE,
                    BC.COLL_ANY_INFO_TO_DISTING,
                    BC.COLL_MARKET_VALUE, BC.COLL_REGISTRY_NO, BC.COLL_REGISTRY_DATE, BC.COLL_REGISTRY_AGENCY, BC.VLR,
                    BC.ORG_ID,
                    BC.OIA_FOR_LAST_THREE_MONTHS, BC.CREDIT_CLASS_CODE, BC.DAYS_INTEREST_IS_OVERDUE, BC.LOAN_ID,
                    BC.IS_NEW,
                    BC.LOAN_DATE_OF_CLOSE, BC.BORROWER_ID, BC.IDM, BC.LOAN_TYPE, BC.LOAN_STATUS, BC.BOR_GRP_NO,
                    BC.BOR_GRP_NAME,
                    BC.TARG_BORROWER_ID);

        DELETE FROM BCP_CREDIT BC WHERE BC.EXEC_ID = EXECUTE_ID;

    END MERGE_CREDIT;


END ARC_PKG;
