ALTER TABLE BCP_BORROWER RENAME TO "BCP_BORROWER_ARC";

CREATE TABLE "ACCR"."BCP_BORROWER"
(
    "OID"            NUMBER(19, 0),
    "CREDIT_ID"      NUMBER(19, 0),
    "EXEC_ID"        NUMBER(19, 0),
    "ACCOUNT_NO"     VARCHAR2(45 CHAR),
    "ROL"            CHAR(1 CHAR),
    "ID"             VARCHAR2(40 CHAR),
    "NAME"           VARCHAR2(100 CHAR),
    "COUNTRY_CODE"   VARCHAR2(10 CHAR),
    "DATE_OF_BIRTH"  VARCHAR2(16 CHAR),
    "PLACE_OF_BIRTH" VARCHAR2(80 CHAR),
    "PIN_CODE"       VARCHAR2(20 CHAR),
    "DOC_TYPE"       NUMBER(19, 0),
    "VLR"            VARCHAR2(10 CHAR),
    "ORG_ID"         NUMBER(19, 0),
    "PERSON_TYPE"    VARCHAR2(14 CHAR),
    "PERSON_ID"      NUMBER(19, 0),
    "IS_NEW"         NUMBER(1, 0)
)
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    STORAGE
(
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
