ALTER TABLE BCP_CREDIT RENAME TO "BCP_CREDIT_ARC";

CREATE TABLE "ACCR"."BCP_CREDIT"
(
    "OID"                       NUMBER(19, 0),
    "EXEC_ID"                   NUMBER(19, 0),
    "ACCOUNT_NO"                VARCHAR2(45 CHAR),
    "CURRENCY_OF_CREDIT"        VARCHAR2(10 CHAR),
    "CREDIT_TYPE"               VARCHAR2(10 CHAR),
    "INITIAL_AMOUNT_OF_CREDIT"  VARCHAR2(16 CHAR),
    "CREDIT_LINE_AMOUNT"        VARCHAR2(16 CHAR),
    "DISOUT_AMOUNT_OF_CREDIT"   VARCHAR2(16 CHAR),
    "ANNUAL_INTEREST_RATE"      VARCHAR2(16 CHAR),
    "PURPOSE_OF_CREDIT"         VARCHAR2(10 CHAR),
    "CREDIT_PERIOD_IN_MONTHS"   VARCHAR2(16 CHAR),
    "DATE_OF_GRANT"             VARCHAR2(16 CHAR),
    "DUE_TIME_FIRST_CONTRACT"   VARCHAR2(16 CHAR),
    "DUE_TIME_LAST_CONTRACT"    VARCHAR2(16 CHAR),
    "LAST_PAYMENT_DATE"         VARCHAR2(16 CHAR),
    "MONTHLY_PAYMENT_AMOUNT"    VARCHAR2(16 CHAR),
    "DAYS_MAIN_SUM_IS_OVERDUE"  VARCHAR2(16 CHAR),
    "OIA_FOR_REPPERIOD"         VARCHAR2(16 CHAR),
    "NUMBER_OF_PROLONGS"        VARCHAR2(16 CHAR),
    "CREDIT_STATUS_CODE"        VARCHAR2(10 CHAR),
    "BANKRUPTCY_STATUS"         VARCHAR2(10 CHAR),
    "COLL_TYPE_CODE"            VARCHAR2(10 CHAR),
    "COLL_ANY_INFO_TO_DISTING"  VARCHAR2(100 CHAR),
    "COLL_MARKET_VALUE"         VARCHAR2(16 CHAR),
    "COLL_REGISTRY_NO"          VARCHAR2(50 CHAR),
    "COLL_REGISTRY_DATE"        VARCHAR2(16 CHAR),
    "COLL_REGISTRY_AGENCY"      VARCHAR2(50 CHAR),
    "VLR"                       VARCHAR2(10 CHAR),
    "ORG_ID"                    NUMBER(19, 0),
    "OIA_FOR_LAST_THREE_MONTHS" VARCHAR2(16 CHAR),
    "CREDIT_CLASS_CODE"         VARCHAR2(10 CHAR),
    "DAYS_INTEREST_IS_OVERDUE"  VARCHAR2(16 CHAR),
    "LOAN_ID"                   NUMBER(19, 0),
    "IS_NEW"                    NUMBER(1, 0),
    "LOAN_DATE_OF_CLOSE"        DATE,
    "BORROWER_ID"               NUMBER(19, 0),
    "IDM"                       CHAR(1 CHAR),
    "LOAN_TYPE"                 VARCHAR2(14 CHAR),
    "LOAN_STATUS"               VARCHAR2(10 CHAR),
    "BOR_GRP_NO"                VARCHAR2(30 CHAR),
    "BOR_GRP_NAME"              VARCHAR2(40 CHAR),
    "TARG_BORROWER_ID"          NUMBER(19, 0)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS NOLOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
